-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 13:48:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myclublife
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myclublife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myclublife` DEFAULT CHARACTER SET utf8 ;
USE `myclublife` ;

-- -----------------------------------------------------
-- Table `myclublife`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`User` (
  `Username` VARCHAR(20) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Filed of Study` VARCHAR(10) NOT NULL,
  `Full Name` VARCHAR(45) NOT NULL,
  `Club Name` VARCHAR(45) NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `Password_UNIQUE` (`Password` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Admin` (
  `User_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`User_Username`),
  CONSTRAINT `fk_Admin_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `myclublife`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Club Manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Club Manager` (
  `User_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`User_Username`),
  CONSTRAINT `fk_Club Manager_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `myclublife`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Student` (
  `User_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`User_Username`),
  CONSTRAINT `fk_Student_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `myclublife`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Club Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Club Member` (
  `User_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`User_Username`),
  CONSTRAINT `fk_Club Member_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `myclublife`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Club` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Score` FLOAT NULL,
  `AVGRating` FLOAT NULL,
  `Club Manager_User_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`, `Club Manager_User_Username`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_Club_Club Manager1_idx` (`Club Manager_User_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Club_Club Manager1`
    FOREIGN KEY (`Club Manager_User_Username`)
    REFERENCES `myclublife`.`Club Manager` (`User_Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Event` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `WinnerClubID` INT NOT NULL,
  `Admin_User_Username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`, `Admin_User_Username`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  UNIQUE INDEX `WinnerClubID_UNIQUE` (`WinnerClubID` ASC) VISIBLE,
  INDEX `fk_Event_Admin1_idx` (`Admin_User_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Event_Admin1`
    FOREIGN KEY (`Admin_User_Username`)
    REFERENCES `myclublife`.`Admin` (`User_Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`Participation` (
  `Event_ID` INT NOT NULL,
  `Club_ID` INT NOT NULL,
  `Club_Club Manager_User_Username` VARCHAR(20) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`Event_ID`, `Club_ID`, `Club_Club Manager_User_Username`),
  INDEX `fk_Event_has_Club_Club1_idx` (`Club_ID` ASC, `Club_Club Manager_User_Username` ASC) VISIBLE,
  INDEX `fk_Event_has_Club_Event1_idx` (`Event_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Event_has_Club_Event1`
    FOREIGN KEY (`Event_ID`)
    REFERENCES `myclublife`.`Event` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Event_has_Club_Club1`
    FOREIGN KEY (`Club_ID` , `Club_Club Manager_User_Username`)
    REFERENCES `myclublife`.`Club` (`ID` , `Club Manager_User_Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`JoinRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myclublife`.`JoinRequest` (
  `Club_ID` INT NOT NULL,
  `Club_Club Manager_User_Username` VARCHAR(20) NOT NULL,
  `Student_User_Username` VARCHAR(20) NOT NULL,
  `ID` INT NOT NULL,
  `Reason` LONGTEXT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Club_ID`, `Club_Club Manager_User_Username`, `Student_User_Username`, `ID`),
  INDEX `fk_Club_has_Student_Student1_idx` (`Student_User_Username` ASC) VISIBLE,
  INDEX `fk_Club_has_Student_Club1_idx` (`Club_ID` ASC, `Club_Club Manager_User_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Club_has_Student_Club1`
    FOREIGN KEY (`Club_ID` , `Club_Club Manager_User_Username`)
    REFERENCES `myclublife`.`Club` (`ID` , `Club Manager_User_Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_has_Student_Student1`
    FOREIGN KEY (`Student_User_Username`)
    REFERENCES `myclublife`.`Student` (`User_Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
