-- MySQL Script generated by MySQL Workbench
-- Sat Apr 29 12:10:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myclublife
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myclublife` ;

-- -----------------------------------------------------
-- Schema myclublife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myclublife` DEFAULT CHARACTER SET utf8 ;
USE `myclublife` ;

-- -----------------------------------------------------
-- Table `myclublife`.`Club Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Club Manager` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Club Manager` (
  `cmID` INT NOT NULL AUTO_INCREMENT,
  `cm_username` VARCHAR(20) NOT NULL,
  `cm_password` VARCHAR(45) NOT NULL,
  `cm_name` VARCHAR(50) NOT NULL,
  `cm_grade` VARCHAR(20) NOT NULL,
  `cm_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cmID`),
  UNIQUE INDEX `cm_username_UNIQUE` (`cm_username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Club` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Club` (
  `clubID` INT NOT NULL AUTO_INCREMENT,
  `club_name` VARCHAR(50) NOT NULL,
  `club_logo` VARCHAR(500) NULL,
  `club_summary` VARCHAR(250) NULL,
  `club_field` VARCHAR(45) NULL,
  `club_creation_date` DATE NULL,
  `Club Manager_cmID` INT NOT NULL,
  `Rating` FLOAT NOT NULL DEFAULT 0,
  `Score` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`clubID`, `Club Manager_cmID`),
  INDEX `fk_Club_Club Manager1_idx` (`Club Manager_cmID` ASC) VISIBLE,
  CONSTRAINT `fk_Club_Club Manager1`
    FOREIGN KEY (`Club Manager_cmID`)
    REFERENCES `myclublife`.`Club Manager` (`cmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Student` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Student` (
  `studentID` INT NOT NULL AUTO_INCREMENT,
  `student_username` VARCHAR(20) NOT NULL,
  `student_password` VARCHAR(45) NOT NULL,
  `student_name` VARCHAR(50) NOT NULL,
  `student_grade` VARCHAR(20) NOT NULL,
  `student_email` VARCHAR(50) NOT NULL,
  `Club_clubID` INT NULL,
  PRIMARY KEY (`studentID`),
  INDEX `fk_Student_Club1_idx` (`Club_clubID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Club1`
    FOREIGN KEY (`Club_clubID`)
    REFERENCES `myclublife`.`Club` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Admin` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Admin` (
  `adminID` INT NOT NULL AUTO_INCREMENT,
  `admin_username` VARCHAR(20) NOT NULL,
  `admin_password` VARCHAR(45) NOT NULL,
  `admin_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`adminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Join Requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Join Requests` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Join Requests` (
  `requestID` INT NOT NULL AUTO_INCREMENT,
  `request_date` DATE NOT NULL,
  `request_reason` VARCHAR(200) NULL,
  `Student_studentID` INT NOT NULL,
  `request_status` VARCHAR(10) NOT NULL DEFAULT 'Pending',
  `Club Manager_cmID` INT NOT NULL,
  PRIMARY KEY (`requestID`),
  INDEX `fk_Join Requests_Student_idx` (`Student_studentID` ASC) VISIBLE,
  INDEX `fk_Join Requests_Club Manager1_idx` (`Club Manager_cmID` ASC) VISIBLE,
  CONSTRAINT `fk_Join Requests_Student`
    FOREIGN KEY (`Student_studentID`)
    REFERENCES `myclublife`.`Student` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Join Requests_Club Manager1`
    FOREIGN KEY (`Club Manager_cmID`)
    REFERENCES `myclublife`.`Club Manager` (`cmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Event` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Event` (
  `eventID` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NOT NULL,
  `event_category` VARCHAR(45) NOT NULL,
  `event_location` VARCHAR(100) NOT NULL,
  `event_logo` VARCHAR(500) NULL,
  `event_startdate` DATE NOT NULL,
  `event_enddate` DATE NOT NULL,
  `Admin_adminID` INT NOT NULL,
  PRIMARY KEY (`eventID`, `Admin_adminID`),
  INDEX `fk_Event_Admin1_idx` (`Admin_adminID` ASC) VISIBLE,
  CONSTRAINT `fk_Event_Admin1`
    FOREIGN KEY (`Admin_adminID`)
    REFERENCES `myclublife`.`Admin` (`adminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Event Participations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Event Participations` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Event Participations` (
  `Club_clubID` INT NOT NULL,
  `Club_Club Manager_cmID` INT NOT NULL,
  `Event_eventID` INT NOT NULL,
  `Event_Admin_adminID` INT NOT NULL,
  `rank` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Club_clubID`, `Club_Club Manager_cmID`, `Event_eventID`, `Event_Admin_adminID`),
  INDEX `fk_Club_has_Event_Event1_idx` (`Event_eventID` ASC, `Event_Admin_adminID` ASC) VISIBLE,
  INDEX `fk_Club_has_Event_Club1_idx` (`Club_clubID` ASC, `Club_Club Manager_cmID` ASC) VISIBLE,
  CONSTRAINT `fk_Club_has_Event_Club1`
    FOREIGN KEY (`Club_clubID` , `Club_Club Manager_cmID`)
    REFERENCES `myclublife`.`Club` (`clubID` , `Club Manager_cmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Club_has_Event_Event1`
    FOREIGN KEY (`Event_eventID` , `Event_Admin_adminID`)
    REFERENCES `myclublife`.`Event` (`eventID` , `Admin_adminID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Club Ratings and Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Club Ratings and Reviews` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Club Ratings and Reviews` (
  `Student_studentID` INT NOT NULL,
  `Club_clubID` INT NOT NULL,
  `Club_Club Manager_cmID` INT NOT NULL,
  `Rating` INT NOT NULL DEFAULT 0,
  `Review` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`Student_studentID`, `Club_clubID`, `Club_Club Manager_cmID`),
  INDEX `fk_Student_has_Club_Club1_idx` (`Club_clubID` ASC, `Club_Club Manager_cmID` ASC) VISIBLE,
  INDEX `fk_Student_has_Club_Student1_idx` (`Student_studentID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Club_Student1`
    FOREIGN KEY (`Student_studentID`)
    REFERENCES `myclublife`.`Student` (`studentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Club_Club1`
    FOREIGN KEY (`Club_clubID` , `Club_Club Manager_cmID`)
    REFERENCES `myclublife`.`Club` (`clubID` , `Club Manager_cmID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
