-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 22:52:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myclublife
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `myclublife` ;

-- -----------------------------------------------------
-- Schema myclublife
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myclublife` DEFAULT CHARACTER SET utf8 ;
USE `myclublife` ;

-- -----------------------------------------------------
-- Table `myclublife`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Users` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Users` (
  `userID` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fullname` VARCHAR(50) NOT NULL,
  `grade` VARCHAR(10) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Clubs_clubID` INT NOT NULL,
  PRIMARY KEY (`userID`),
  UNIQUE INDEX `Username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_Users_Clubs_idx` (`Clubs_clubID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Clubs`
    FOREIGN KEY (`Clubs_clubID`)
    REFERENCES `myclublife`.`Clubs` (`clubID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`ClubManagers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`ClubManagers` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`ClubManagers` (
  `Users_userID` INT NOT NULL,
  `student_requests` VARCHAR(500) NULL,
  PRIMARY KEY (`Users_userID`),
  CONSTRAINT `fk_ClubManagers_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `myclublife`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Clubs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Clubs` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Clubs` (
  `clubID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `rating` FLOAT NULL,
  `logo` VARCHAR(100) NULL,
  `ClubManagers_Users_userID` INT NOT NULL,
  `reviews` VARCHAR(1000) NULL,
  `members` VARCHAR(500) NULL,
  PRIMARY KEY (`clubID`, `ClubManagers_Users_userID`),
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_Clubs_ClubManagers1_idx` (`ClubManagers_Users_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Clubs_ClubManagers1`
    FOREIGN KEY (`ClubManagers_Users_userID`)
    REFERENCES `myclublife`.`ClubManagers` (`Users_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Admins` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Admins` (
  `Users_userID` INT NOT NULL,
  PRIMARY KEY (`Users_userID`),
  CONSTRAINT `fk_Admins_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `myclublife`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Students` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Students` (
  `Users_userID` INT NOT NULL,
  PRIMARY KEY (`Users_userID`),
  CONSTRAINT `fk_Students_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `myclublife`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`Events` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`Events` (
  `eventID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `logo` VARCHAR(100) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `Admins_Users_userID` INT NOT NULL,
  PRIMARY KEY (`eventID`),
  INDEX `fk_Events_Admins1_idx` (`Admins_Users_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Events_Admins1`
    FOREIGN KEY (`Admins_Users_userID`)
    REFERENCES `myclublife`.`Admins` (`Users_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`EventParticipants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`EventParticipants` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`EventParticipants` (
  `Events_eventID` INT NOT NULL,
  `Clubs_clubID` INT NOT NULL,
  `Clubs_ClubManagers_Users_userID` INT NOT NULL,
  `score` FLOAT NULL,
  `rank` INT NULL,
  `prize` VARCHAR(45) NULL,
  PRIMARY KEY (`Events_eventID`, `Clubs_clubID`, `Clubs_ClubManagers_Users_userID`),
  INDEX `fk_Events_has_Clubs_Clubs1_idx` (`Clubs_clubID` ASC, `Clubs_ClubManagers_Users_userID` ASC) VISIBLE,
  INDEX `fk_Events_has_Clubs_Events1_idx` (`Events_eventID` ASC) VISIBLE,
  CONSTRAINT `fk_Events_has_Clubs_Events1`
    FOREIGN KEY (`Events_eventID`)
    REFERENCES `myclublife`.`Events` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Clubs_Clubs1`
    FOREIGN KEY (`Clubs_clubID` , `Clubs_ClubManagers_Users_userID`)
    REFERENCES `myclublife`.`Clubs` (`clubID` , `ClubManagers_Users_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myclublife`.`JoinRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `myclublife`.`JoinRequests` ;

CREATE TABLE IF NOT EXISTS `myclublife`.`JoinRequests` (
  `Clubs_clubID` INT NOT NULL,
  `Clubs_ClubManagers_Users_userID` INT NOT NULL,
  `Students_Users_userID` INT NOT NULL,
  `date` DATE NULL,
  `reason` VARCHAR(100) NULL,
  `status` VARCHAR(20) NULL,
  PRIMARY KEY (`Clubs_clubID`, `Clubs_ClubManagers_Users_userID`, `Students_Users_userID`),
  INDEX `fk_Clubs_has_Students_Students1_idx` (`Students_Users_userID` ASC) VISIBLE,
  INDEX `fk_Clubs_has_Students_Clubs1_idx` (`Clubs_clubID` ASC, `Clubs_ClubManagers_Users_userID` ASC) VISIBLE,
  CONSTRAINT `fk_Clubs_has_Students_Clubs1`
    FOREIGN KEY (`Clubs_clubID` , `Clubs_ClubManagers_Users_userID`)
    REFERENCES `myclublife`.`Clubs` (`clubID` , `ClubManagers_Users_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clubs_has_Students_Students1`
    FOREIGN KEY (`Students_Users_userID`)
    REFERENCES `myclublife`.`Students` (`Users_userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
